---
- debug:
    msg: "{{ ruby_sources_url }}"

- name: Ruby binary
  stat:
    path: "{{ ruby_dir }}/bin/ruby"
  register: ruby_bin

- name: Download ruby sources
  unarchive:
    src: "{{ ruby_sources_url }}"
    dest: "{{ sources_dir }}"
    remote_src: "yes"
    creates: "{{ ruby_sources_dir }}/configure"
  when: not ruby_bin.stat.exists

- name: Install build deps
  apt:
    name:
      - build-essential
      - libgmp-dev
      - libreadline6-dev
      - libssl-dev
      - zlib1g-dev
    update_cache: yes
  when: not ruby_bin.stat.exists

- name: Configure
  shell:
    chdir: "{{ ruby_sources_dir }}"
    creates: "{{ ruby_sources_dir }}/Makefile"
    cmd: "./configure --prefix {{ ruby_dir }}"
  when: not ruby_bin.stat.exists

- name: Install ruby
  make:
    chdir: "{{ ruby_sources_dir }}"
    target: "install"
  when: not ruby_bin.stat.exists

- name: Update .bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH={{ ruby_dir }}/bin:$PATH"
    create: yes
  when: not ruby_bin.stat.exists
